### ISSUE TITLE
ESLINT 정책 설정

### ISSUE THREAD

**Issue by wdjty326** [wdjty326/wdjty326.github.io#1]

**Comment by ngchinhan011** [comment]
![Ewtkx5fWYAMyHAY](https://user-images.githubusercontent.com/123218538/216731864-ad43fd8f-601c-4884-b671-9d553a0ce409.jpg)
![B3jnFawCIAAAQ5A](https://user-images.githubusercontent.com/123218538/216731904-29491335-33f3-4989-8fdc-a0d2f877627b.jpg)
![Uploading 19875222_745644388930308_902463259805996886_n.jpg…]()
